server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: vibecoding-backend
  
  profiles:
    active: dev
  
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://45.192.104.100:3306/vibecoding?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: mysql_xPDZKR
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: VibecodingHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  
  # Redis配置
  data:
    redis:
      host: 45.192.104.100
      port: 6379
      password: redis_ZfJsEw
      database: 0
      timeout: 6000ms
      jedis:
        pool:
          max-active: 10
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
  
  # 邮件配置
  mail:
    host: smtp.163.com
    port: 465
    username: noreply_vibecoding@yeah.net
    password: XKS95ZQAFRnvGtRb
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  
  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    # 是否开启自动驼峰命名规则映射
    map-underscore-to-camel-case: true
    # 开启Mybatis二级缓存
    cache-enabled: false
    # 配置JdbcTypeForNull
    jdbc-type-for-null: 'null'
    # 打印SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.vibecoding.vibecoding_backend.entity
  
  # mapper文件扫描路径
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  
  # 全局配置
  global-config:
    # 数据库相关配置
    db-config:
      # 主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID" ID_WORKER:"全局唯一ID" UUID:"全局唯一ID"
      id-type: AUTO
      # 字段策略 IGNORED:"忽略判断" NOT_NULL:"非 NULL 判断") NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      # 驼峰下划线转换
      column-underline: true
      # 逻辑删除配置
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
    # 是否控制台打印
    banner: true

# 日志配置
logging:
  level:
    com.vibecoding.vibecoding_backend: DEBUG
    org.springframework.security: DEBUG
    com.baomidou.mybatisplus: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'
  file:
    name: logs/vibecoding-backend.log

  # 应用自定义配置
app:
  jwt:
    secret: vibecoding-jwt-secret-key-202406-very-long-and-secure-key-for-production-use-at-least-256-bits
    expiration: 86400000 # 24小时
  
  file:
    upload-path: /uploads/
    max-size: 10485760 # 10MB
    download-base-url: http://localhost:8080 # 开发环境默认URL
    storage-path: filesource
    output-path: filetarget
  
  # Dify配置
  dify:
    base-url: https://dify.aistudio.ltd/v1
    bearer-token: app-blj7fVtI82UlI0HWyberMKe4
    workflow-path: /workflows/run
    interface-name: getresumeinfo
    connect-timeout: 10000
    read-timeout: 30000
  
  cors:
    allowed-origins: 
      - http://localhost:3000
      - http://localhost:5173
      - http://localhost:8080
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers: "*"
    allow-credentials: true

---
# 开发环境配置
spring:
  config:
    activate:
      on-profile: dev
      
  datasource:
    url: jdbc:mysql://45.192.104.100:3306/vibecoding_dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: mysql_xPDZKR

  data:
    redis:
      host: 45.192.104.100
      port: 6379
      password: redis_ZfJsEw
      database: 0

app:
  file:
    download-base-url: https://vibecoding-api.aistudio.ltd

logging:
  level:
    root: INFO
    com.vibecoding.vibecoding_backend: DEBUG

---
# 生产环境配置
spring:
  config:
    activate:
      on-profile: prod
      
  datasource:
    url: jdbc:mysql://localhost:3306/vibecoding_prod?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 1

app:
  file:
    download-base-url: ${FILE_DOWNLOAD_BASE_URL:https://your-domain.com}

logging:
  level:
    root: WARN
    com.vibecoding.vibecoding_backend: INFO
  file:
    name: /var/log/vibecoding-backend/application.log